name: Publish
on:
  push:
  release:
    types: [ published ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      LAVALINK_MAVEN_USERNAME: ${{ secrets.LAVALINK_MAVEN_USERNAME }}
      LAVALINK_MAVEN_PASSWORD: ${{ secrets.LAVALINK_MAVEN_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Build and Publish
        run: ./gradlew build publish --no-daemon -PMAVEN_USERNAME=$MAVEN_USERNAME -PMAVEN_PASSWORD=$MAVEN_PASSWORD -PLAVALINK_MAVEN_USERNAME=$LAVALINK_MAVEN_USERNAME -PLAVALINK_MAVEN_PASSWORD=$LAVALINK_MAVEN_PASSWORD

      - name: Upload main Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LavaLyrics.jar
          path: main/build/libs/lavalyrics-*.jar

      - name: Upload plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LavaLyrics-Plugin.jar
          path: plugin/build/libs/lavalyrics-plugin-*.jar
          
      - name: Upload plugin-api Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LavaLyrics-Plugin-API.jar
          path: plugin-api/build/libs/lavalyrics-plugin-api-*.jar
          
      - name: Upload protocol Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LavaLyrics-Protocol.jar
          path: protocol/build/libs/lavalyrics-protocol-*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download main Artifact
        uses: actions/download-artifact@v4
        with:
          name: LavaLyrics.jar

      - name: Download plugin Artifact
        uses: actions/download-artifact@v4
        with:
          name: LavaLyrics-Plugin.jar

      - name: Download plugin-api Artifact
        uses: actions/download-artifact@v4
        with:
          name: LavaLyrics-Plugin-API.jar

      - name: Download protocol Artifact
        uses: actions/download-artifact@v4
        with:
          name: LavaLyrics-Protocol.jar

      - name: Upload Artifacts to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: lavalyrics-*.jar
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true